"""Widget layout configuration — generated by UI Editor."""
ORIENTATION = "portrait"
ROTATION = 0

WIDGETS = [
    {"type": "Button", "x": 75, "y": 125, "w": 105, "h": 80, "label": "BTN 1", "osc_addr": "/esp32/button/1"},
]