import { useState } from 'react'

export default function ExportButton({ widgets, orientation = 'portrait' }) {
  const [status, setStatus] = useState('')

  const generateCode = () => {
    if (widgets.length === 0) return ''

    const lines = []

    for (const w of widgets) {
      let args = `"type": "${w.type}", "x": ${w.x}, "y": ${w.y}, "w": ${w.w}, "h": ${w.h}`
      if (w.type === 'Button' && w.label) {
        args += `, "label": "${w.label}"`
      }
      args += `, "osc_addr": "${w.osc_addr}"`
      if ((w.type === 'Slider' || w.type === 'HSlider') && w.default != null) {
        args += `, "default": ${Number(w.default)}`
      }
      if (w.type === 'HSVPicker' && Array.isArray(w.default)) {
        args += `, "default": (${w.default.join(', ')})`
      }
      lines.push(`    {${args}},`)
    }

    const rotation = orientation === 'landscape' ? 1 : 0

    return `"""Widget layout configuration — generated by UI Editor."""\nORIENTATION = "${orientation}"\nROTATION = ${rotation}\n\nWIDGETS = [\n${lines.join('\n')}\n]`
  }

  const showStatus = (msg) => {
    setStatus(msg)
    setTimeout(() => setStatus(''), 2000)
  }

  const handleDownload = () => {
    const code = generateCode()
    if (!code) {
      showStatus('ウィジェットがありません')
      return
    }

    const blob = new Blob([code], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'widgets.py'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    showStatus('ダウンロードしました')
  }

  const handleCopy = async () => {
    const code = generateCode()
    if (!code) {
      showStatus('ウィジェットがありません')
      return
    }

    try {
      await navigator.clipboard.writeText(code)
      showStatus('クリップボードにコピーしました')
    } catch {
      showStatus('コピーに失敗しました')
    }
  }

  return (
    <div className="export-group">
      <button className="export-btn" onClick={handleDownload}>
        ⬇ widgets.py ダウンロード
      </button>
      <button className="export-btn" onClick={handleCopy}>
        📋 コピー
      </button>
      {status && <span className="export-status">{status}</span>}
    </div>
  )
}
